export { default as registerController } from './registerController'
export { default as otpController } from './otpController'
export { default as depositController } from './depositController'
export { default as loginController } from './loginController'
export { default as depositAddressController } from './depositAddressController'
export { default as modifyDepositAddressController } from './modifyDepositAddressesController'
export { default as refferController } from './refferController'
export { default as plansController } from './plansController'
export { default as withdrawController } from './withdrawController'
export { default as transactionsController } from './transactionsController'
export { default as userController } from './userController'
export { default as adminControllers } from './adminControllers'
export { default as dashBoardController } from './dashBoardController'

